title = "buf0v3rfl0w"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

#[services.disqus]
#	shortname = 'buf0v3rfl0w'

[languages]
  [languages.en]
    title = "buf0v3rfl0w"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "dark-gray"
  author = "Dakota Vickers"
  site_logo = "logo.png"
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  recent_posts_number = 3
  # commentoEnable = true
  show_reading_time = true

[[params.ananke_socials]]
	name = "twitter"
	url = "https://twitter.com/buf0v3rfl0w"

[[params.ananke_socials]]
	name = "github"
	url = "https://github.com/sdvickers98"

[[params.ananke_socials]]
	name = "linkedin"
	url = "https://www.linkedin.com/in/dakota-vickers-90748a190/"

[markup.goldmark.renderer]
	unsafe = true